# Generated by Django 6.0.4 on 2026-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_created_at_users_is_deleted_users_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
